---
- name: F5 BIG-IPS 
  hosts: lb
  connection: local
  gather_facts: False

  vars:
    cancelprecheck: false #F5 precheck 

    provider:
      password: "{{ ansible_ssh_pass }}"
      server: "{{ ansible_host }}"
      user: "{{ ansible_user }}"
      validate_certs: False
  

  tasks:
    
    #Create a Post check of F5 Virtual Server Status
    - name: "Pre-Check 1: Grab the Virtual Server Status"
      bigip_device_facts:
        gather_subset:
        - virtual-servers
        provider: "{{provider}}"
      register: bigip_facts_post

    - name: "Pre-Check 2: Capture the Virtual Server stats in a .json file"
      set_fact:
        result: "{{bigip_facts_post.virtual_servers | json_query(query_string) }}"
      vars:
        query_string: "[*].{Name: name, Status: availability_status,Full_Path: full_path,Destination: destination_address,Destination_Port: destination_port, Protocol: protocol,Pool: default_pool,Persistance: persistence_profile, Status_Reason: status_reason }"

    - debug: "msg={{result}}"  # You can comment this out if you dont want to see the output

    - local_action:
        module: copy
        content: "{{ result }}"
        dest: "outputs/pre-{{ansible_host}}-virtual-servers-outputs.json"

    - name: "Pre-Check 3: Generate F5 Virtual Server Status .html Page"
      template:
        src: ./report/templates/report.j2
        dest: ./report/pre-check-f5.html
      delegate_to: localhost
      run_once: true
