---
- name: Upgrade BIG-IP software
  hosts: lb
  connection: local
  gather_facts: False

  vars:
    install_no_reboot: true
    

    provider:
      password: "{{ bigip_password }}"
      server: "{{ ansible_host }}"
      user: "{{ bigip_username }}"
      validate_certs: False


  tasks:

    - name: Collect information of all virtual servers
      bigip_device_facts:
        gather_subset:
         - virtual-servers
        provider: "{{provider}}"
      register: facts_result

    - name: Display all VIP's available
      debug: "msg={{item.name}}"
      loop: "{{facts_result.virtual_servers}}"
      loop_control:
            label: "{{item.name}}"

    - name: Store the vip name in a variable
      set_fact:
        first_vip_name: "{{facts_result.virtual_servers[1].name}}"
 
    - name: Display all status attached to a VIP "name={{first_vip_name}}"
      debug: "msg={{item}}"
      loop: "{{facts_result.virtual_servers | json_query(query_string)}}"
      vars:
        query_string: "[?name=='{{first_vip_name}}'].availability_status"


    
